module.exports = {
  LOGIN: "LOGIN",
  MOVIE_LIST: "MOVIE_LIST",
  MOVIE_FILTER: 'MOVIE_FILTER',
  MOVIE_SORT: 'MOVIE_SORT',
  SET_MOVIE_FILTER: 'SET_MOVIE_FILTER',
  SET_MOVIE_SORT: 'SET_MOVIE_SORT',
  RESET_MOVIE_FILTER: 'RESET_MOVIE_FILTER',
  RESET_MOVIE_SORT: 'RESET_MOVIE_SORT',
  TITLE: 'Title',
  LANGUAGE: 'Language',
  LOCATION: 'Location'
};
